cc_binary(
    name = "hello_world",
    srcs = ["HelloWorld.cpp"],
    deps = [
        "@boost//:algorithm",
        "@boost//:core",
        "@com_github_glog_glog//:glog",
        "@com_github_libfmt_fmt//:fmt",
    ],
)
